const enum Action {
    Open = 'open',
    Pin = 'pin',
    Unpin = 'unpin',
    Rate = 'rate',
    Info = 'info',
    Download = 'download',
    RemoveDownload = 'remove-download',
    AddToLibrary = 'library-add',
    RemoveFromLibrary = 'library-remove',
    AddStation = 'station-add',
    EditStation = 'station-edit',
    RemoveStation = 'station-remove',
    PlayNow = 'play-now',
    PlayNext = 'play-next',
    Queue = 'queue',
    AddToPlaylist = 'add-to-playlist',
    AddToNewPlaylist = 'add-to-new-playlist',
    AddToRecentPlaylist1 = 'add-to-recent-playlist-1',
    AddToRecentPlaylist2 = 'add-to-recent-playlist-2',
    AddToRecentPlaylist3 = 'add-to-recent-playlist-3',
    AddToRecentPlaylist4 = 'add-to-recent-playlist-4',
    DeletePlaylist = 'delete-playlist',
    DeletePlaylistItems = 'delete-playlist-items',
    EditPlaylist = 'edit-playlist',
}

export default Action;
